name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules
          npm cache clean --force
          npm ci --prefer-offline

      - name: Build project (with permissions fixed)
        run: |
          chmod +x ./node_modules/.bin/run-p
          npm run build-only

      - name: Compress build artifacts
        run: |
          cd dist
          find . -name "*.js" -exec gzip -k -f {} \;
          find . -name "*.css" -exec gzip -k -f {} \;
          find . -name "*.html" -exec gzip -k -f {} \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          enable_jekyll: false
          allow_empty_commit: false
          keep_files: false
          force_orphan: true